apiVersion: v1 # The API version for core Kubernetes objects like Services.
kind: Service # Declares that you are creating a Service resource.
metadata: # Data to identify the Service.
  name: nginx-internal # The name of this Service.
spec: # The specification for the Service.
  ports: # Defines the service's network ports.
  - name: http # A name for the port mapping.
    port: 8000 # The port that the Service itself will expose.
    protocol: TCP # The network protocol.
    targetPort: 8000 # The port on the pod that traffic will be forwarded to.
  selector: # How the Service finds which pods to send traffic to.
    service: nginx-server # It selects pods with the label "service: nginx-server".
  type: ClusterIP # The type of service. ClusterIP is only reachable from within the cluster.
