apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: <your-django-image>
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_NAME
          value: books
        - name: DATABASE_USER
          value: books
        - name: DATABASE_PASSWORD
          value: books
        - name: DATABASE_HOST
          value: postgres
        - name: DEVELOPMENT_MODE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-app 