# Generated by Django 5.2.4 on 2025-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field',
            field=models.CharField(default='new_field', max_length=255),
        ),
    ]
